# =============================================================================
# interpolate_lidar.py
#
# Interpolate LiDAR elevations from multiple ESRI ASCII grids (.asc)
# onto transect points generated by generate_transects.py
# =============================================================================

import os
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio
from rasterio.crs import CRS
from tqdm import tqdm

# =============================================================================
# USER PARAMETERS
# =============================================================================

# CSV produced by the transect generation script
TRANSECT_CSV = r"/path/to/transects.csv"

# Root directory containing all LiDAR tiles
# The script will search recursively in all subfolders.
LIDAR_ROOT = r"/path/to/LiDAR"

# Output CSV
OUTPUT_CSV = r"/path/to/transects_with_depth.csv"

# CRS of the transect coordinates
# Use the same CRS used to generate the transects.
TRANSECT_CRS = CRS.from_epsg(4326)

# Bilinear interpolation (recommended)
# Alternatives: "nearest", "bilinear"
INTERPOLATION = "bilinear"

# Value written when a point falls outside every raster
NODATA_VALUE = np.nan

# Print progress information
VERBOSE = True

# =============================================================================
# SEARCH RECURSIVELY FOR ALL ASCII FILES
# =============================================================================

print("Searching for LiDAR ASCII grids...")

asc_files = sorted(Path(LIDAR_ROOT).rglob("*.asc"))

if len(asc_files) == 0:
    raise FileNotFoundError(
        f"No .asc files found under:\n{LIDAR_ROOT}"
    )

print(f"Found {len(asc_files)} ASCII grids.\n")

# Print file names (optional)
if VERBOSE:
    for f in asc_files:
        print(f)
# =============================================================================
# BUILD SPATIAL INDEX OF ALL RASTER TILES
# =============================================================================

from shapely.geometry import box
from shapely.strtree import STRtree
from pyproj import Transformer

print("\nOpening LiDAR rasters and building spatial index...")

# List that will contain all raster information
raster_info = []

# Geometry list used to build the STRtree
raster_boxes = []

# Coordinate transformers (created only if needed)
transformers = {}

for asc_file in tqdm(asc_files):

    src = rasterio.open(asc_file)

    # Bounding box of the raster
    bounds = src.bounds

    bbox = box(
        bounds.left,
        bounds.bottom,
        bounds.right,
        bounds.top
    )

    raster_boxes.append(bbox)

    raster_info.append({

        "file": asc_file,

        "dataset": src,

        "bounds": bounds,

        "bbox": bbox,

        "crs": src.crs,

        "transform": src.transform,

        "nodata": src.nodata

    })

# -------------------------------------------------------------------------
# Build STRtree
# -------------------------------------------------------------------------

tree = STRtree(raster_boxes)

# Dictionary linking each geometry to its raster information
bbox_lookup = {
    id(info["bbox"]): info
    for info in raster_info
}

print(f"\nSpatial index built with {len(raster_info)} raster tiles.")

# -------------------------------------------------------------------------
# Compute overall LiDAR coverage
# -------------------------------------------------------------------------

xmin = min(r["bounds"].left for r in raster_info)
xmax = max(r["bounds"].right for r in raster_info)

ymin = min(r["bounds"].bottom for r in raster_info)
ymax = max(r["bounds"].top for r in raster_info)

print("\nLiDAR coverage")

print(f"X : {xmin:.2f}  --> {xmax:.2f}")
print(f"Y : {ymin:.2f}  --> {ymax:.2f}")

# -------------------------------------------------------------------------
# Prepare CRS transformers
# -------------------------------------------------------------------------

for info in raster_info:

    crs_string = info["crs"].to_string()

    if crs_string not in transformers:

        transformers[crs_string] = Transformer.from_crs(
            TRANSECT_CRS,
            info["crs"],
            always_xy=True
        )

print(f"\nPrepared {len(transformers)} coordinate transformer(s).")
# =============================================================================
# LOAD TRANSECT POINTS
# =============================================================================

from shapely.geometry import Point
from rasterio.enums import Resampling

print("\nLoading transect points...")

transects = pd.read_csv(TRANSECT_CSV)

# Add output column
transects["depth"] = NODATA_VALUE

print(f"{len(transects)} transect points loaded.")

# =============================================================================
# INTERPOLATION FUNCTION
# =============================================================================

def interpolate_point(lon, lat):

    # Search point (transects are stored in WGS84)
    pt_wgs84 = Point(lon, lat)

    # Candidate raster bounding boxes
    candidate_boxes = tree.query(pt_wgs84)

    if len(candidate_boxes) == 0:
        return NODATA_VALUE

    # Test only candidate rasters
    for bbox in candidate_boxes:

        info = bbox_lookup[id(bbox)]

        transformer = transformers[info["crs"].to_string()]

        # Transform coordinates to raster CRS
        x, y = transformer.transform(lon, lat)

        # Reject if outside raster
        if not info["bbox"].contains(Point(x, y)):
            continue

        try:

            value = list(
                info["dataset"].sample(
                    [(x, y)],
                    indexes=1
                )
            )[0][0]

        except Exception:
            continue

        # Ignore NoData
        if info["nodata"] is not None:

            if np.isclose(value, info["nodata"]):

                return NODATA_VALUE

        return float(value)

    return NODATA_VALUE


# =============================================================================
# INTERPOLATE ALL TRANSECT POINTS
# =============================================================================

print("\nInterpolating LiDAR elevations...")

for i in tqdm(range(len(transects))):

    lon = transects.at[i, "lon"]
    lat = transects.at[i, "lat"]

    z = interpolate_point(lon, lat)

    transects.at[i, "depth"] = z

# =============================================================================
# SUMMARY
# =============================================================================

n_valid = transects["depth"].notna().sum()

n_nan = transects["depth"].isna().sum()

print()

print("--------------------------------")

print(f"Interpolated points : {n_valid}")

print(f"Outside LiDAR       : {n_nan}")

print("--------------------------------")

# =============================================================================
# SAVE CSV
# =============================================================================

transects.to_csv(
    OUTPUT_CSV,
    index=False,
    float_format="%.3f"
)

print()

print(f"Saved to\n{OUTPUT_CSV}")

# =============================================================================
# CLOSE ALL RASTERS
# =============================================================================

for info in raster_info:

    info["dataset"].close()

print("\nFinished.")
